//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBASync.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VBASyncResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VBASyncResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VBASync.Localization.VBASyncResources", typeof(VBASyncResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alt+F4.
        /// </summary>
        public static string AltF4 {
            get {
                return ResourceManager.GetString("AltF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Apply.
        /// </summary>
        public static string ApplyAction {
            get {
                return ResourceManager.GetString("ApplyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initial project byt Chelsea Hughes..
        /// </summary>
        public static string AWCopyright {
            get {
                return ResourceManager.GetString("AWCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About VBA Sync Tool.
        /// </summary>
        public static string AWTitle {
            get {
                return ResourceManager.GetString("AWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VBA Sync Tool.
        /// </summary>
        public static string AWVBASyncTool {
            get {
                return ResourceManager.GetString("AWVBASyncTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version {0}.
        /// </summary>
        public static string AWVersion {
            get {
                return ResourceManager.GetString("AWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GitHub {0}.
        /// </summary>
        public static string AWWebsite {
            get {
                return ResourceManager.GetString("AWWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronizes macros from an Office VBA-enabled file with a version-controlled folder..
        /// </summary>
        public static string AWWTFIsThis {
            get {
                return ResourceManager.GetString("AWWTFIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Browse.
        /// </summary>
        public static string BrowseAction {
            get {
                return ResourceManager.GetString("BrowseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelAction {
            get {
                return ResourceManager.GetString("CancelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} → {1} and file changed ({2}).
        /// </summary>
        public static string CDChangeFileType {
            get {
                return ResourceManager.GetString("CDChangeFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File changed ({0}).
        /// </summary>
        public static string CDWholeFile {
            get {
                return ResourceManager.GetString("CDWholeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add file.
        /// </summary>
        public static string CTAddFile {
            get {
                return ResourceManager.GetString("CTAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string CTAddLines {
            get {
                return ResourceManager.GetString("CTAddLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Sub.
        /// </summary>
        public static string CTAddSub {
            get {
                return ResourceManager.GetString("CTAddSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module type.
        /// </summary>
        public static string CTChangeFileType {
            get {
                return ResourceManager.GetString("CTChangeFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Form design.
        /// </summary>
        public static string CTChangeFormControls {
            get {
                return ResourceManager.GetString("CTChangeFormControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change.
        /// </summary>
        public static string CTChangeLines {
            get {
                return ResourceManager.GetString("CTChangeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete file.
        /// </summary>
        public static string CTDeleteFile {
            get {
                return ResourceManager.GetString("CTDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete form design.
        /// </summary>
        public static string CTDeleteFrx {
            get {
                return ResourceManager.GetString("CTDeleteFrx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string CTDeleteLines {
            get {
                return ResourceManager.GetString("CTDeleteLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Sub.
        /// </summary>
        public static string CTDeleteSub {
            get {
                return ResourceManager.GetString("CTDeleteSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licenses.
        /// </summary>
        public static string CTLicenses {
            get {
                return ResourceManager.GetString("CTLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename file.
        /// </summary>
        public static string CTMoveFile {
            get {
                return ResourceManager.GetString("CTMoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move Sub.
        /// </summary>
        public static string CTMoveSub {
            get {
                return ResourceManager.GetString("CTMoveSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project.
        /// </summary>
        public static string CTProject {
            get {
                return ResourceManager.GetString("CTProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace.
        /// </summary>
        public static string CTReplaceId {
            get {
                return ResourceManager.GetString("CTReplaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl+L.
        /// </summary>
        public static string CtrlL {
            get {
                return ResourceManager.GetString("CtrlL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl+O.
        /// </summary>
        public static string CtrlO {
            get {
                return ResourceManager.GetString("CtrlO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl+S.
        /// </summary>
        public static string CtrlS {
            get {
                return ResourceManager.GetString("CtrlS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module.
        /// </summary>
        public static string CTWholeFile {
            get {
                return ResourceManager.GetString("CTWholeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot find &apos;vbaProject.bin&apos; in ZIP archive..
        /// </summary>
        public static string ErrorCannotFindVbaProject {
            get {
                return ResourceManager.GetString("ErrorCannotFindVbaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot load WPF UI. If your system is non-Windows or otherwise doesn&apos;t support WPF, you may only run VBA Sync Tool by specifying -r on the command-line..
        /// </summary>
        public static string ErrorCannotLoadGUI {
            get {
                return ResourceManager.GetString("ErrorCannotLoadGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while decompressing stream &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorDecompressingStream {
            get {
                return ResourceManager.GetString("ErrorDecompressingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error creating OleColor: expected 4 bytes but saw {0} bytes as read..
        /// </summary>
        public static string ErrorFrxColorSizeMismatch {
            get {
                return ResourceManager.GetString("ErrorFrxColorSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expected end of OleSiteConcreteControl..
        /// </summary>
        public static string ErrorFrxExpectedEndOfOleSiteConcreteControl {
            get {
                return ResourceManager.GetString("ErrorFrxExpectedEndOfOleSiteConcreteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error reading &apos;{0}&apos; stream in .frx data: expected {1} size {2}, but saw {3} bytes as read..
        /// </summary>
        public static string ErrorFrxStreamSizeMismatch {
            get {
                return ResourceManager.GetString("ErrorFrxStreamSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path to file cannot be null or empty..
        /// </summary>
        public static string ErrorPathCannotbeNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorPathCannotbeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unrecognized module type..
        /// </summary>
        public static string ErrorUnrecognizedModuleType {
            get {
                return ResourceManager.GetString("ErrorUnrecognizedModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Different stream lists in storage &apos;{0}&apos;.
        ///
        ///File 1: {{&apos;{1}&apos;}}
        ///
        ///File 2: {{&apos;{2}&apos;}}.
        /// </summary>
        public static string ExplainFrxDifferentFileLists {
            get {
                return ResourceManager.GetString("ExplainFrxDifferentFileLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Different contents of stream &apos;{0}&apos; in storage &apos;{1}&apos;..
        /// </summary>
        public static string ExplainFrxGeneralStreamDifference {
            get {
                return ResourceManager.GetString("ExplainFrxGeneralStreamDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Different contents of stream &apos;o&apos;, site &apos;{0}&apos; in storage &apos;{1}&apos;..
        /// </summary>
        public static string ExplainFrxOStreamDifference {
            get {
                return ResourceManager.GetString("ExplainFrxOStreamDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FRX file difference.
        /// </summary>
        public static string ExplainFrxTitle {
            get {
                return ResourceManager.GetString("ExplainFrxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Class.
        /// </summary>
        public static string MTClass {
            get {
                return ResourceManager.GetString("MTClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Form.
        /// </summary>
        public static string MTForm {
            get {
                return ResourceManager.GetString("MTForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project.
        /// </summary>
        public static string MTIni {
            get {
                return ResourceManager.GetString("MTIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licenses.
        /// </summary>
        public static string MTLicenses {
            get {
                return ResourceManager.GetString("MTLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module.
        /// </summary>
        public static string MTStandard {
            get {
                return ResourceManager.GetString("MTStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document.
        /// </summary>
        public static string MTStaticClass {
            get {
                return ResourceManager.GetString("MTStaticClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _About VBA Sync Tool.
        /// </summary>
        public static string MWAboutMenu {
            get {
                return ResourceManager.GetString("MWAboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        public static string MWActionText {
            get {
                return ResourceManager.GetString("MWActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change type.
        /// </summary>
        public static string MWChangeType {
            get {
                return ResourceManager.GetString("MWChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string MWDescription {
            get {
                return ResourceManager.GetString("MWDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Edit.
        /// </summary>
        public static string MWEditMenu {
            get {
                return ResourceManager.GetString("MWEditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E_xit.
        /// </summary>
        public static string MWExitMenu {
            get {
                return ResourceManager.GetString("MWExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E_xtract VBA from Office file.
        /// </summary>
        public static string MWExtract {
            get {
                return ResourceManager.GetString("MWExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _File.
        /// </summary>
        public static string MWFileMenu {
            get {
                return ResourceManager.GetString("MWFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Help.
        /// </summary>
        public static string MWHelpMenu {
            get {
                return ResourceManager.GetString("MWHelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Load last session.
        /// </summary>
        public static string MWLoadLastMenu {
            get {
                return ResourceManager.GetString("MWLoadLastMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Open session.
        /// </summary>
        public static string MWLoadSessionMenu {
            get {
                return ResourceManager.GetString("MWLoadSessionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module.
        /// </summary>
        public static string MWModule {
            get {
                return ResourceManager.GetString("MWModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Office file.
        /// </summary>
        public static string MWOfficeFile {
            get {
                return ResourceManager.GetString("MWOfficeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All files.
        /// </summary>
        public static string MWOpenAllFiles {
            get {
                return ResourceManager.GetString("MWOpenAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All supported files.
        /// </summary>
        public static string MWOpenAllSupported {
            get {
                return ResourceManager.GetString("MWOpenAllSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Excel 2007+ files.
        /// </summary>
        public static string MWOpenExcel07 {
            get {
                return ResourceManager.GetString("MWOpenExcel07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Excel 97-2003 files.
        /// </summary>
        public static string MWOpenExcel97 {
            get {
                return ResourceManager.GetString("MWOpenExcel97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outlook files.
        /// </summary>
        public static string MWOpenOutlook {
            get {
                return ResourceManager.GetString("MWOpenOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PowerPoint 2007+ files.
        /// </summary>
        public static string MWOpenPpt07 {
            get {
                return ResourceManager.GetString("MWOpenPpt07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stand-alone VBA project.
        /// </summary>
        public static string MWOpenSAlone {
            get {
                return ResourceManager.GetString("MWOpenSAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session files.
        /// </summary>
        public static string MWOpenSession {
            get {
                return ResourceManager.GetString("MWOpenSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word 2007+ files.
        /// </summary>
        public static string MWOpenWord07 {
            get {
                return ResourceManager.GetString("MWOpenWord07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word 97-2003 files.
        /// </summary>
        public static string MWOpenWord97 {
            get {
                return ResourceManager.GetString("MWOpenWord97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Publish VBA to Office file.
        /// </summary>
        public static string MWPublish {
            get {
                return ResourceManager.GetString("MWPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Refresh.
        /// </summary>
        public static string MWRefreshAction {
            get {
                return ResourceManager.GetString("MWRefreshAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Save session.
        /// </summary>
        public static string MWSaveSessionMenu {
            get {
                return ResourceManager.GetString("MWSaveSessionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Settings.
        /// </summary>
        public static string MWSettingsMenu {
            get {
                return ResourceManager.GetString("MWSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VBA Sync Tool.
        /// </summary>
        public static string MWTitle {
            get {
                return ResourceManager.GetString("MWTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _VBA project folder.
        /// </summary>
        public static string MWVBAFolder {
            get {
                return ResourceManager.GetString("MWVBAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string OKAction {
            get {
                return ResourceManager.GetString("OKAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow adding new document modules when publishing (expert option).
        /// </summary>
        public static string SWAddNewDocumentsToFile {
            get {
                return ResourceManager.GetString("SWAddNewDocumentsToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à After-extract hook.
        /// </summary>
        public static string SWAfterExtractHook {
            get {
                return ResourceManager.GetString("SWAfterExtractHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Macros: {TargetDir}.
        /// </summary>
        public static string SWAfterExtractHookHelp {
            get {
                return ResourceManager.GetString("SWAfterExtractHookHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Before-publish hook.
        /// </summary>
        public static string SWBeforePublishHook {
            get {
                return ResourceManager.GetString("SWBeforePublishHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Macros: {TargetDir}.
        /// </summary>
        public static string SWBeforePublishHookHelp {
            get {
                return ResourceManager.GetString("SWBeforePublishHookHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow deleting document modules when publishing (expert option).
        /// </summary>
        public static string SWDeleteDocumentsFromFile {
            get {
                return ResourceManager.GetString("SWDeleteDocumentsFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Diff tool (optional).
        /// </summary>
        public static string SWDiffTool {
            get {
                return ResourceManager.GetString("SWDiffTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D_iff tool parameters.
        /// </summary>
        public static string SWDiffToolParameters {
            get {
                return ResourceManager.GetString("SWDiffToolParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Macros: {OldFile}, {NewFile}.
        /// </summary>
        public static string SWDiffToolParametersHelp {
            get {
                return ResourceManager.GetString("SWDiffToolParametersHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General.
        /// </summary>
        public static string SWGeneralTab {
            get {
                return ResourceManager.GetString("SWGeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore empty modules.
        /// </summary>
        public static string SWIgnoreEmpty {
            get {
                return ResourceManager.GetString("SWIgnoreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Language (requires restart).
        /// </summary>
        public static string SWLanguage {
            get {
                return ResourceManager.GetString("SWLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load last session at startup.
        /// </summary>
        public static string SWLoadLastSessionAtStartup {
            get {
                return ResourceManager.GetString("SWLoadLastSessionAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Applications.
        /// </summary>
        public static string SWOpenApplications {
            get {
                return ResourceManager.GetString("SWOpenApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search subdirectories of VBA project folder.
        /// </summary>
        public static string SWSearchRepositorySubdirectories {
            get {
                return ResourceManager.GetString("SWSearchRepositorySubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session.
        /// </summary>
        public static string SWSessionTab {
            get {
                return ResourceManager.GetString("SWSessionTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SWTitle {
            get {
                return ResourceManager.GetString("SWTitle", resourceCulture);
            }
        }
    }
}
